# Generated by Django 5.2.5 on 2025-08-12 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID Contacto"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="ejemplo@gmail.com",
                        max_length=50,
                        verbose_name="Correo",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=64, verbose_name="Nombre"),
                ),
                ("message", models.TextField(verbose_name="Descripcion")),
            ],
        ),
    ]
