services:
  - type: web
    name: proyecto-tienda-virtual
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn onlyflans.wsgi:application

    preDeploy:
      - python manage.py migrate
      - python manage.py collectstatic --noinput
