services:
  - type: web
    name: proyecto-tienda-virtual
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --verbosity=2
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn onlyflans.wsgi:application
