services:
  - type: web
    name: proyecto-tienda-virtual
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn onlyflans.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: onlyflans.settings

    preDeploy:
      - python manage.py migrate --noinput
      - python manage.py loaddata web/fixtures/flanes.json
