services:
  - type: web
    name: proyecto-tienda-virtual
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py loaddata flanes
      python manage.py collectstatic --noinput
      mkdir -p staticfiles/media
      cp -r media/productos staticfiles/media/
    startCommand: python manage.py migrate --noinput && gunicorn onlyflans.wsgi:application
