# Generated by Django 5.2.5 on 2025-08-08 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flan",
            fields=[
                (
                    "flan_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nombre")),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "imagen",
                    models.ImageField(upload_to="productos/", verbose_name="Imagen"),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Privado"),
                ),
            ],
        ),
    ]
