# Generated by Django 5.2.5 on 2025-08-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flan",
        ),
    ]
