# Generated by Django 5.2.5 on 2025-08-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flan",
        ),
    ]
