# Generated by Django 5.2.5 on 2025-08-08 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web", "0004_delete_flan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flan",
            fields=[
                (
                    "flan_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nombre")),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="Precio"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="productos/", verbose_name="Imagen"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Privado"),
                ),
            ],
        ),
    ]
