# Generated by Django 5.2.5 on 2025-08-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_contactform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
