# Generated by Django 5.2.5 on 2025-08-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_contactform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
