# Generated by Django 5.2.6 on 2025-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_delete_contactform"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Unidades disponibles", verbose_name="Stock"
            ),
        ),
    ]
